# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

hex4/legged_gym:
  model_name: "model.pt"
  num_observations: 85
  observations: ["lin_vel","ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions", "hex4/phase"]
  observations_history: []  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,  -100.0,
                       -100.0, -100.0, -100.0,  -100.0,
                       -100.0, -100.0, -100.0,  -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0]
  rl_kp: [100.0, 100.0, 100.0, 100.0,
          100.0, 100.0, 100.0, 100.0,
          100.0, 100.0, 100.0, 100.0,
          100.0, 100.0, 100.0, 100.0,
          100.0, 100.0, 100.0, 100.0,
          100.0, 100.0, 100.0, 100.0]
  rl_kd: [1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2]
  fixed_kp: [160.0, 160.0, 160.0, 160.0,
                160.0, 160.0, 160.0, 160.0,
                160.0, 160.0, 160.0, 160.0,
                160.0, 160.0, 160.0, 160.0,
                160.0, 160.0, 160.0, 160.0,
                160.0, 160.0, 160.0, 160.0]
  fixed_kd: [1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2,
                1.2, 1.2, 1.2, 1.2]
  num_of_dofs: 24
  action_scale: [0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25,]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [60.0, 60.0, 60.0, 60.0,
                  60.0, 60.0, 60.0, 60.0,
                  60.0, 60.0, 60.0, 60.0,
                  60.0, 60.0, 60.0, 60.0,
                  60.0, 60.0, 60.0, 60.0,
                  60.0, 60.0, 60.0, 60.0]
  default_dof_pos: [ 0.0,0.0,-0.5,2.0,
                     0.0,0.0,-0.5,2.0,
                     0.0,0.0,-0.5,2.0,
                     0.0,0.0,-0.5,2.0,
                     0.0,0.0,-0.5,2.0,
                     0.0,0.0,-0.5,2.0]
  feet_indices: [3,7,11,15,19,23]

  # joint_mapping: [4,5,6,7,
  #                 8,9,10,11,
  #                 0,1,2,3,
  #                 16,17,18,19,
  #                 12,13,14,15,
  #                 20,21,22,23
  #                 ]

  # joint_mapping: [8,9,10,11,
  #                 0,1,2,3,
  #                 4,5,6,7,
  #                 20,21,22,23,
  #                 12,13,14,15,
  #                 16,17,18,19
  #                 ]
  joint_mapping: [
                  20,21,22,23,
                  12,13,14,15,
                  16,17,18,19,
                  8,9,10,11,
                  0,1,2,3,
                  4,5,6,7,
                  ] 